branches:
  except:
  - developer
language: node_js
node_js:
  - "8"
script:
 - echo "Deploy from GIITHUB, I'm so happy y contento !!"
install:
  - npm install -g firebase-tools
  - cd ./functions/ && npm install  
after_success:
  - firebase deploy  --project angular-crud-firebase-9d4e9 --only functions --token $FIREBASE_TOKEN --debug
